---
title: "Ten Uses and Four Misuses of Commas in English (plus Use 11)"
author: "Ethan Weed"
date: "2/28/2020"
output: 
  revealjs::revealjs_presentation:
    theme: night
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 10 Correct Commas Uses

Press \<space\> to advance, and \<shift\> + \<space\> to go back

## Use #1: 
### Combining two independent clauses joined with a coordinating conjunction.
<br><br>
This might be the only chance you get to skydive, so you better make the most of it. 

Coordinating conjunctions: 
and, but, for, or, nor, so, yet

## Use #2: 
### Separating three or more items in a series.
<br><br>
Three things Ethan likes are coding, biking, and drinking coffee. 


## Use #3: 
### Setting off introductory phrases or clauses.
<br><br>
To prepare for his new life in the monestary, Ethan gave away all of his worldly possesions.


## Use #4: 
### Setting off one or more words that interrupt the flow of thought in a sentence (non-defining relative clauses).
<br><br>
The man, who has an office just down the hall from me, knows a lot about languages from the Kimberley region in Australia.

BUT:

The man who has an office just down the hall from me knows a lot about languages from the Kimberley region in Australia.

## Use #5: 
### Separating two or more adjectives that modify the same noun, if you can substitute the word *and* for the comma.
<br><br>
Bash&#333; was a master of the subtle, delicate art of haiku.

## Use #6: 
### Separating two clauses if a dependent marker is used to start the sentence.
<br><br>
If you want make an omlette, you have to crack some eggs. 

BUT

You have to crack some eggs if you want to make an omlette.

BUT

I had to crack some eggs, although I didn't want to make an omlette.


## Use #7: 
### Setting off direct quotes.
<br><br>
The zombie said, “I like turtles!” 

## Use #8: 
### Setting off introductory words.
<br><br>
First, I need to think of a good sentence for this example.  
However, I am having a hard time coming up with one.

## Use #9: 
### Setting off years in full dates, titles in names, and regions.
<br><br>
November 22, 1963, John Fitzgerald Kennedy, the 35th President of the United States, was assassinated in Dallas, Texas.

## Use #10: 
### Setting off names in direct address.
<br><br>
“Just because it’s taken you three years to notice, Ron, doesn't mean no one *else* has spotted I'm a girl!” 


# Common Comma Misuses

## Misuse #1:
### Separating the subject and the predicate.
<br><br>
*Getting to work on time, can be difficult. 

## Misuse #2: 
### Separating a verb and its object.
<br><br>
*I was watching, the news.

*I want to ask, if you will do me a favor.

## Misuse #3: 
### Putting a comma in a compound subject or predicate with 2 items.
<br><br>
*Jack, and Jill went up the hill, and ate enchiladas.

## Misuse #4: 
### Using one comma to set off an "interrupter".
<br><br>
*Spot, the dog who resucued Timmy is a hero.

BUT:

Spot, the dog who rescued Timmy, is a hero.  
Spot the dog, who rescued Timmy, is a hero.

## Use 11

## Use 11

Use commas *wherever necessary* to prevent possible confusion or misreading.


## The "Oxford" or "Serial" comma

- *According to some style guides, Use #2 can be optional* 

- Three things Ethan likes are coding, biking, and drinking coffee. 
- Three things Ethan likes are coding, biking and drinking coffee. 

- *The Problem:*<br>
"I am a huge fan of my grandparents, Shakira and Spongebob." <br><br>

- *The Oxford/Serial Comma Solution:*<br>
"I am a huge fan of my grandparents, Shakira, and Spongebob." <br><br>

- *The "Just Write a Better Sentence" Solution:*<br>
"I am a huge fan of Shakira, Spongebob and my grandparents." <br><br>


## Practice with Commas
Directions: Put commas where they belong. A few of these sentences do not need commas.

1. We are having peas and carrots roast beef and cake for dinner.
2. Dr. Pfizer my physician says I should take better care of my health.
3. My 4th grade teacher always said “Remember Ethan use commas before and after you address someone directly.”
4. Piglet said “Did you see the Heffalump?”
5. The teachers at Aarhus University try hard to use commas correctly.
6. Tom painted the fence white blue and green.
7. We waited at the bus stop on Park Allé after school.
8. My mom who is a nurse cares for the sick injured and disabled.
9. One famous basketball player Michael Jordan won five MVP awards.
10. "Well we were always going to fail that one" said Ron gloomily as they ascended the marble staircase.


## Practice with Commas  
11. Robert Louis Stevenson was a Scottish writer of novels poems and essays.
12. Now Mr. Bond we will saw you in half. 
13. They crawled into a forest like the big unlucky mammals they were.
14. Chicago the largest city in the Midwest is the home of the skyscraper blues and deep-dish pizza.
15. No Mr. Krabs I don’t want your secret recipe.
16. Alice said “Why, sometimes I've believed as many as six impossible things before breakfast.”
17. Emilio my next-door neighbor has two daughters a son and a puppy.
18. That Tuesday which also happens to be my birthday is the only day we can take the test.
19. Fred who often cheats on his homework is really only harming himself. 
20. Martin Braithwaite the footballer was just hired by Barcelona.


## Commas vs. semicolons
Semicolon or Comma?
Directions: determine whether the clauses need to be joined with commas or semicolons. Put the
proper punctuation on the blank.

1. The artist preferred to paint in oils ____ he did not like watercolors.
2. Even when the house looks clean ____ there is usually a bunch of dirt swept under the rug.
3. I’m going to leave early today ____ unless the boss comes back from the meeting.
4. The computer can perform many calculations at once ____ however, it cannot reason like a human.
5. In the first place, it was snowing too hard to see the road ____ in the second place, we had no chains. 

## Commas vs. semicolons  
6. The challenges are not impossible ___ but they are very hard to clear.
7. I’m going to do all of my English homework every night ____ because that’s how you get an “A”.
8. If he misses his appointment ____ he’ll have to wait another six months to see the dentist.
9. There are many negative side effects to smoking ___ there are no positive side effects from smoking.

## Resources

### Purdue (aka The Bible)
https://owl.purdue.edu/owl/general_writing/punctuation/commas/index.html

### Down-to-earth guidelines with lots of examples (where I stole most of this from)
https://www.ereadingworksheets.com/languageartsworksheets/punctuationworksheets/comma-worksheets/

### Some useful tips on subordinate clauses
http://theeditorsblog.net/2014/07/30/commas-with-subordinate-clauses-a-readers-question/
