---
output: html_document
---

# Work Log

### Today I...

#### 2019.03.19
1. Answered emails
1. Submitted meta-analysis manuscript (!)
1. Moved online CV to an Rmd file for easier updating of markdown -> html
1. Updated CV
1. Began modelling dyslexia / history of reading disability data for RSC

####  2019.03.18
1. Looked into the idea of livestreaming journal article reading as a teaching tool
1. Did final preparation for article submission: figure captions, abstract, author info, ORCID profile updating, publisher profile updating, etc. etc.
1. Attempted to send receipts to accounting office (only partially successful, website started timing out)
1. Reviewed current projects and culled old and completed projects
1. Treated myself to a bagel to celebrate acceptance of first Dyslexia article
1. Finally got around to adding python scripts to OSF for Hearing You Hearing Me article

#### 2019.03.15
1. Met with collaborators to discuss design for upcoming pilot EEG project
1. Started a shared draft with collaborators on ASD voice project
1. Cleaned up analysis code from meta-analysis for posting on OSF
1. Formatted references for meta-analysis paper
1. Produced high-res images for meta-analysis paper

#### 2019.03.14
1. Gave comments on PhD application
1. Gave comments on a grant application
1. Researched multivariate mixed-effects Bayesian modelling
1. Completed and sent article review

#### 2019.03.13
1. Reviewed tutorial on lme4
1. Researched methods for conducting power analysis on mixed-effects models
1. Went through tutorial for the simr package
1. Discovered that the read.csv function in R can read from a URL, but semmingly not if the file is stored on GitHub

#### 2019.03.12
1. Gave feedback on PhD application
1. Continued editing meta-analysis paper
1. Researched options for anonymously linking to code and data during peer review and settled on OSF, which can generate a view-only link

#### 2019.03.11
1. Caught up on email
1. Arranged travel to upcoming conference
1. Reviewed status on all projects
1. Began final edits on meta-analysis prior to submission

#### 2019.03.07
1. Wrote a Praat script to extract jitter and shimmer
1. Added jitter and shimmer to ASD voice analysis

#### 2019.03.06
1. Caught up on email
1. Gave feedback on a conference abstract and a PhD proposal
1. Updated conda env to allow gui's from PsychoPy
1. Worked on editing PsychoPy script for upcoming data collection

#### 2019.03.05
1. Met with a collaborator to plan analyses for an article
1. Worked on wrangling data: matching ID numbers up with diagnostic info
1. Gave exam feedback
1. Set up conda environment for editing psychopy code in jupyter notebooks

#### 2019.03.03
1. Reviewed progress during first month of sabbatical
1. Thought a bit about changes to next semesters stats teaching

#### 2019.02.29
1. Started a new repo for cross-linguistic ASD project
1. Started writing data-wrangling script to organize data for analysis
1. Experimented with mixing R and Python within a single .Rmd file

#### 2019.02.28
1. Had a Skype meeting with research collaborators
1. More data sifting and orienting
1. Meeting with collaborators on task selection / modification for upcoming study

#### 2019.02.27
1. Answered emails
1. Went to journal club presentation
1. Gave feedback on MA thesis draft
1. Researched LASSO and elasticnet feature selection
1. Oriented myself in data and code for upcoming article
1. Some exam grading

#### 2019.02.26
1. Finished article draft and sent to co-author

#### 2019.02.25
1. Did MA thesis advising
1. Answered emails
1. Arranged conference practicalities
1. Went to a student talk
1. Worked on discussion section for an article
1. Updated Stroop dataset on GitHub
1. Found a small but important error and re-ran meta-analysis

#### 2019.02.24
1. Wrote a bash and python combo to batch normalize the volume on a directory of sound files

#### 2019.02.22
1. Wrote a Praat script to batch low-pass filter speech stimuli
1. Wrote a shell script to batch boost the volume of sound files with ffmpeg
1. Revised results table to include p-values as well as Bayesian stats
1. Added seeds to model definitions for stable results on multiple runs
1. Wrote first draft of discussion section for meta-analysis

#### 2019.02.21
1. Wrote emails
1. Read and commented on an MA thesis draft
1. Read more of the manuscript I am reviewing
1. Edited meta-analysis script to output data in a different format
1. Made a table with meta-analysis data

#### 2019.02.20 
1. Answered emails
1. Re-worked sections of meta-analysis
1. Added a new script to compare RHD participants with LHD participants
1. Re-arranged folder structure for meta-analysis git repo
1. Took out and re-wrote sections of RHD paper draft
1. Played with using R-markdown as a means of generating html files for my website
1. Began reading a manuscript for review
1. Started this work log
1. Learned how to make an html table from csv in R with kabelExtra
